;; ==========================================================
;; Modules Configuration
;; ==========================================================

[modules]
autoload=yes

; 必要なモジュール
load = res_pjsip.so
load = res_pjsip_transport_websocket.so
load = res_pjsip_sdp_rtp.so
load = res_pjsip_session.so
load = res_pjsip_endpoint_identifier_user.so
load = res_pjsip_authenticator_digest.so
load = res_pjsip_registrar.so
load = res_http_websocket.so
load = codec_opus.so

; 不要なモジュールを無効化
noload = chan_sip.so
noload = res_hep.so
noload = res_hep_pjsip.so
noload = res_hep_rtcp.so
